<?php

// Auto generated by Fusion News v3.9.5

$fusion_id = 'i8w2a1jn7Zvox4JFkEq210jRnLlNqNU7';
$site = 'http://ubec.obscureserver.com/';
$furl = 'http://ubec.obscureserver.com/news';
$hurl = 'http://ubec.obscureserver.com/';
$datefor = 'Y-m-d';
$numofposts = 3;
$numofh = 5;
$bb = 1;
$ht = 1;
$post_per_day = 0;
$wfpost = 1;
$wfcom = 1;
$skin = 'simplicity';
$smilies = 1;
$stfpop = 1;
$comallowbr = 1;
$stfwidth = 640;
$stfheight = 480;
$fslink = 'read more...';
$stflink = 'tell a friend';
$pclink = 'comments';
$fsnw = 1;
$cbflood = 1;
$floodtime = 30;
$comlength = 300;
$fullnewsw = 640;
$fullnewsh = 480;
$fullnewss = 1;
$stfresize = 1;
$stfscrolls = 1;
$fullnewsz = 1;
$htc = 0;
$smilcom = 1;
$bbc = 0;
$compop = 1;
$comscrolls = 1;
$comresize = 1;
$comheight = 480;
$comwidth = 640;
$uploads_active = 0;
$uploads_size = 1048576;
$uploads_ext = 'gif|jpg|jpeg|png|bmp';
$enable_rss = 1;
$link_headline_fullstory = 1;
$flip_news = 0;
$rss_title = '';
$rss_description = '';
$rss_encoding = 'utf-8';
$com_validation = 0;
$com_captcha = 1;
$news_pagination = 1;
$news_pagination_prv = '&lt;&lt; Prev';
$news_pagination_nxt = 'Next &gt;&gt;';
$news_pagination_numbers = 1;
$news_pagination_arrows = 1;
$ppp_date = 'jS F Y';
$comments_pages = 1;
$comments_per_page = 10;

?>